rogov-dvp/medical-imaging-matching

- docs/pull_request_template.md
This is the body of the "pull_request_template_primary.md" file
This is now an edit, v1.
> Third update

- docs/pull_request_template.md
This is the body of the "pull_request_template_primary.md" file
This is now an edit, v1.
This is now an edit, v3.
> Update to pull_request_template.md

- README.md
Issue fix: # (issue)
Added description for project and team information to readme.
Change has been previewed locally, update will not break formatting of readme.
> Added description and team information to readme

- docs/gitstats-Niklas/October.md
Issue fix: #32
Add issue 32 to docs
> add issue 32 to docs

- docs/gitstats-alex/october.md
- docs/gitstats-alex/october.txt
Issue fix: #23 
DFD Level 0 presentation slides
> Gitstats alex/issue 23

- docs/gitstats-Niklas/October.md
Issue fix: #25
Include issue 25 to docs ( feature requirements)
> Add Issue 25 to docs

- docs/team_meeting_notes/week3.md
- docs/team_meeting_notes/week4.md
- docs/team_meeting_notes/week5.md
Adding team meeting notes to repo.
> added team meeting notes to repo

- docs/project_requirements/requirements_group_feedback/group_evaluations.md
Issue fix: #60 
Included Feedback for the LIMS Project
> Feedback added for LIMS

- docs/team_meeting_notes/week8.md
- docs/team_meeting_notes/week9.md
> week8 team meeting notes

- docs/data_preprocessing/data_augmentation.md
- docs/team_meeting_notes/week8.md
> Research Data augmentation

- docs/data_preprocessing/data_cleaning.md
- preprocessing/data_augmentation.py
- preprocessing/data_cleaning.py
- requirements-dev.txt
- requirements_dev.txt
Added notes about data cleaning methods and exploration
Issue fix: #114
> Data cleaning

- preprocessing/da_unit_testing.py
Issue fix: #120 
Please delete options that are not relevant.
> unit test framework formatting - skeleton

- preprocessing/data_cleaning.py
Issue fix: #112 
Some work on my skeleton code for data cleaning specifically adding implementations for finding the percentage of missing data values.
Please delete options that are not relevant.
-  [x] I have commented my code, particularly in hard-to-understand areas
> Code for data cleaning, missing data values.. still needs work

- src/models/siamese.py
- src/models/siamese2.py
Found two Siamese code examples
Issue fix: #117
> Siamese exploration and got some working test code

- README.md
- docs/script_integration.md
> documentation on script integrations

- docs/Models/siamese_networks.md
Added a file for documenting siamese networks 
Issue fix: #146
> Siamese networks Documentation

- docs/Models/siamese_networks.md
- src/models/siamese2_unit_testing.py
- src/models/siamese_unit_testing.py
Testing skeleton added for Siamese Networks will update code once siamese implementation is completed 
Issue fix: #142
> Siamese unit testing implementation

- src/models/ORB.py
- src/models/SSIM.py
SSIM and ORB models code refactored, updated a bit to our case, and commented for clearer understanding.
Issue fix: #138
> SSIM and ORB code refactored, updated a bit to our case, and commented for clearer understanding

- src/models/ORB_test.py
- src/models/SSIM.py
- src/models/SSIM_test.py
Created unit tests for both SSIM and ORB.
Additionally, added good source for adding args to run files in cli code. Ie. code that allows us to run the file and add arguments (image pathways) directly from the CLI. Currently, commented out. This information is located in SSIM.py 
Issue fix: #143
> Created unit tests for both SSIM and ORB. Also potential CLI-related code

- docs/Models/siamese_networks.md
- src/models/siamese2.py
Working on the implementation of siamese networks in order to get a percentage similarity return
Issue fix: #140
> Siamese implementation

- docs/gitstats-marieke/Novemeber.md
Updated November.MD file for peer testing
Issue fix: #163
> Git stats November 

- docs/gitstats-emily/november.md
Issue fix: #162 
Noted work done by me this week.
> gitstats report on my work this week

- docs/gitstats-marieke/Novemeber.md
Add notes on pdf report 
Issue fix: #165
> Update November.md for report

- docs/testing_to_do.md
Issue fix: #166 
Adding notes on testing that needs to be done on all the scripts that we currently have.
> adding notes on testing that needs to be done

- docs/gitstats-emily/december.md
Issue fix: #187 
- Notes on what I have completed this week.
> progress notes

- docs/gitstats-marieke/December.md
Add word done this week to December gitstats 
Issue fix: #186
> Add Progress this week

- docs/gitstats-Niklas/Report.md
Add the report to my other weekly reports, on what I did the last week.
Issue fix: #167
> Add Reporting for the Last Week

- preprocessing/data_cleaning.py
- preprocessing/data_cleaning_test.py
Implemented tests required for data cleaning script
Issue fix: #190
> Data cleaning tests 

- src/training/models/siamese2.py
- src/training/models/test_siamese2.py
- src/training/models/tests_siamese2.py
Spent some time working on implementing testing for siamese 2, need to continue to work on over the break as I also improve the model itself this is just a basis to go off
Issue fix: #194
> Exploration on tests for siamese

- src/training/models/BatchBuilder.py
- src/training/models/CNNTripletModel.py
- src/training/models/tests_BatchBuilder.py
- src/training/models/tests_CNNTripletModel.py
Add Testing for the CNNTripletModel and the BatchBuilder
Issue fix: #193
> Implement testing

- src/training/models/tests_ORB.py
- src/training/models/tests_SSIM.py
I fixed unittest issues. I have tested it and It should run properly now 
Issue fix: #191 
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> fixed tests_ORB.py and test_SSIM.py unit tests

- docs/team_meeting_notes/term2/January19.md
> adding team notes

- docs/Models/siamese_networks.md
Added reasons to why CNN is the preferred model in the case of our project.
Issue fix: #214
> updates to doc on siamese networks

- docs/Models/ORB.md
- docs/Models/SSIM.md
Made updates to ORB and SSIM docs stating why CNN is preferred
Issue fix: #211
> Made updates to ORB and SSIM documents of models

- docs/data_preprocessing/image_cropping.md
- preprocessing/preprocess_data.py
Issue fix: #210 
During our client meeting, Rasika mentioned that there may be some issues in the future depending on how the library we used crops/resizes the images. We need to ensure that our choice of library does not impede our model.
As of now, it does not seem like there will be an issue other than varying image sizes and perhaps with aspect ratios. Currently, I would recommend sticking with `cv2.INTER_AREA` interpolation. However, I will be researching more and clarifying with Rasika.
> research into image cropping

- docs/Models/CNN.md
Add details to the adjustments made to the skeleton to fix the transfer learning training issue. 
Add details why we decided to continue working with CNN Architecture
Issue fix: #215
> Add Justification and further details to the models CNN documentation

- docs/exploration/BatchBuilder.md
- docs/exploration/CNN_on_Remote/BatchBuilder.py
Spent time researching Batch building created a document in order to keep track of research, there are some great resources linked to the PDF document I found to be very useful. Been working with the implementation Niklas found trying to see if it will be reusable as a solution for us as well. Going to take a deeper dive over the weekend now that I have a better grasp on what is needed, more on the implementation side hopefully getting a final solution.
Issue fix: #217
> Exploration into the batch builder

- docs/team_meeting_notes/term2/January26.md
Team meeting notes for January 26
Issue fix: #242
> Added notes for this week

- docs/exploration/CNN.py
- docs/exploration/CNN_Tests.py
- src/training/models/CNNTripletModel.py
- src/training/models/tests_CNNTripletModel.py
Improvements made to the testing for the CNN model to go more into depth
Issue fix: #221
> More in-depth testing to CNN

- data/mismatches_remote.csv
- preprocessing/preprocess_data_remote.py
Issue fix: #236 
I have adjusted the preprocessing to read files based on the setup in the server. There is also an issue with one of the libraries on the remote server that I haven't been able to fix yet. So I can't confirm that it is 100% working and can't implement the testing yet.
> Remote preprocessing

- docs/exploration/CNN_on_Remote/BatchBuilder.py
- docs/exploration/NumPy_limitations.md
Some research into limitations we could run into with NumPy files will be doing a deeper dive into specific issues that we may encounter for our project
Issue fix: #245
> NumPy files exploration

- src/training/models/BatchBuilder.py
- src/training/models/CNNTripletModel.py
- src/training/models/Evaluate.py
- src/training/models/MainRead.py
- src/training/models/MainTrain.py
- src/training/models/Read_images.py
- src/training/models/SiameseTriplet.py
- src/training/models/Test.py
Move the relevant code from exploration to models folder
Issue fix: #249
> move model to model folder

- docs/team_meeting_notes/term2/February2.md
Upload team meeting notes for this week
Issue fix: #258
> team notes February 2

- docs/integration/preprocessing_cnn_integration.md
> description of current issues added

- docs/exploration/CNN_on_Remote/BatchBuilder.py
- docs/exploration/NumPy_limitations.md
Added some more specific details to the exploration, as well as numerous sources that give a lot of great input specifically into neural nets and NumPy.
Issue fix: #238
> Added detail to the NumPy exploration file

- docs/exploration/BatchBuilder.md
- docs/exploration/CNN_on_Remote/BatchBuilder.py
- docs/gitstats-marieke/February.md
Added a file for Feb gitstats to keep track of progress, (Thanks to Alex for the inspiration here!) Spent a lot of time on the implementation of the batch building today should be completed by tomorrow, and hopefully, this helps to resolve some issues.
Issue fix: #256
> February gitstats added 

- docs/gitstats-alex/february.md
I got the chance to go send lots of time at school and work on this. However, I ran into  non-stop problems with packages (they were errors in calculation). I plan to go back tomorrow to continue on this.
Issue fix: #257
> Created february file for gistats

- docs/gitstats-Niklas/Report.md
Work on CNN training problems
Issue fix: #254
> Document Progress on Gradient Explosion Progress

- docs/team_meeting_notes/term2/Februrary9.md
Team meeting notes Feb 9
Issue fix: #273
> Upload team meeting notes

- docs/gitstats-marieke/February.md
Updated Feb gitstats to include work done this week, an exploration into integration of batch building 
Issue fix: #272
> Updated Feb gitstats 

- docs/exploration/embedding_issues.md
- docs/gitstats-emily/february.md
Issue fix: #270 
The research on embedding needs background research and documentation done on the triplet loss function for better understanding. The issue will be adjusted and closed to reflect that. A new issue next week will be opened regarding embedding and further research.
> Research on Triplet Loss Encoding/Embedding

- docs/exploration/CNN_on_Remote/siamesenetwork.ipynb
Experiment with the example code from keras to see whether the same error occurs (Spoiler it does :/)
Issue fix: #268
> Add Keras example

- docs/gitstats-marieke/February.md
Added notes on work done this week 
Issue fix: #286
> Work done this week added to Feb md

- docs/gitstats-emily/february.md
> summary of work done this week

- docs/gitstats-alex/february.md
I got code that should have been working with model and it shows a picture without the label. But, I was having issues with the label showing. I think it might be the model which is the issue. I will continue working on this over the reading break 
Issue fix: #295
> This week's progress. I will continue working on this during the week

- docs/gitstats-Niklas/Report.md
Add documentation for this weeks work
Issue fix: #300
> Add documentation on this weeks work

- docs/gitstats-marieke/March.md
Added this week's activities to the March Gitstats
Issue fix: #311
> Updated gitstats for peer testing activities 

- docs/gitstats-alex/march.md
Gitstats documents updated. Created the slides for prototype video #2 for section user interaction and breast detection.
Issue fix: #307
> Updating gitstats documents. Prototype video #2 slides

- docs/gitstats-emily/march.md
> work done in march

- docs/project_requirements/preprocessing.md
> documentation on preprocessing for pt2 done

- docs/gitstats-alex/march.md
Updated march gitstats docs for doing the peer report section: User Interaction and Breast Detection.
Issue fix: #318
> Gitstats march update

- docs/gitstats-marieke/March.md
Add completion of peer reviews to March gitstats
Issue fix: #330
> Updated March git stats to include peer reviews 

- docs/project_requirements/preprocessing.md
Issue fix: #325 
Documentation of preprocessing code as of Peer Testing 2
> documentation for preprocessing added

- docs/gitstats-emily/march.md
> added emily notes for gitstats

- docs/gitstats-Niklas/Report.md
Add reporting for this weeks progress and work on the gpu
Issue fix: #322
> add progress of this week to gitstats report

- docs/gitstats-Niklas/Report.md
Worked on the Peer Report 2/ added comments to the gitstats report
Issue fix: #321
> Add comments to the gitstats documentation

- docs/gitstats-Niklas/Report.md
Finally resolved the big training problem and we can start work on optimisation
Issue fix: #237
> Finally cleared the big training issue

- docs/gitstats-emily/march.md
Issue fix: #340 
Week of March 14, 2022
- Worked on integrating all the features together on the remote server (ie. Preprocessing, Batch Builder, Breast Detection, and Model (CNN))
- Wrote integration tests for the integration of the features
- Researched how to use the hard cases for batch building first.
- created files for final report and presentation
> work so far:

- docs/exploration/embedding_issues.md
> Research into online hard-negative mining

- docs/gitstats-emily/march.md
- docs/integration/script_integration.md
Issue fix: #347 
Added notes on the possible flow for the script integration. I am not entirely sure of the order and use of some of the files so this could be wrong. I am working on the actual integration on the remote server.
> Integration Notes

- preprocessing/breast_detection/crop_main_file.py
- preprocessing/breast_detection/test_crop_main.py
Created unit tests for crop_main_file. As well, made a few changes to crop_main_file.py
Issue fix: #241
> Unit tests for breast detection and some minor changes to breast_detection script

- docs/gitstats-Niklas/Report.md
Report on task completed on the gpu this week
Issue fix: #352
> Weekly report

- docs/team_meeting_notes/term2/March30.md
Added team meeting notes for the week of March 30
Issue fix: #357
> Meeting notes for this week 

- docs/integration/script_integration.md
- preprocessing/preprocess_data.py
- preprocessing/preprocess_test.py
- src/predicting/ims/main.py
- src/predicting/ims/tests_main.py
Issue fix: #359 
Notes on integration testing, integration tests fixed, and preprocess tests fixed.
> integration testing and preprocess testing

- docs/gitstats-Niklas/Report.md
Write test on the gpu
Issue fix: #366
> Report tests written on the gpu

- docs/gitstats-Niklas/Report.md
Train VGG and ResNet
Issue fix: #364
> Report progress and training the models

- docs/gitstats-alex/april.md
Fix package errors for Great Detection on GPU. Still had problems regarding gpu memory.
Issue fix: #368
> Adding gitstats notes for april

- docs/team_meeting_notes/term2/April6.md
Updated team meeting notes for week of April 6 
Issue fix: #370
> Team Meeting Notes 

- docs/gitstats-alex/april.md
Doing research and trying to get remote server to work- gitstats
Issue fix: #373
> Research on breast detection - april gitstats

- docs/gitstats-alex/april.md
Help write the final report
Issue fix: #372
> Add gitsats for final report
